spring:
  data:
    mongodb:
      uri: ${ MONGO_URI :mongodb://localhost:27017 }
      database: ${ MONGO_DATABASE :chat_nexus }

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}
